### PR TITLE
012/training

### PR DESCRIPTION
**Pull request by payne-chris-r**
Went through and re-factored the code so it more closely matched what is done in jquery-ajax-post, delete, and patch. This should allow students to see the same pattern and understand the flow.

### CODE REVIEW

**Comment by jrhorn424** [comment]
This is targeting solution. Was that correct? If so, you should probably name the branch on your fork `012/solution` **in the future**. Please just confirm whether this is the right target. Thanks!

**Comment by payne-chris-r** [comment]
This should definitely be targeting Solution. I'm fine with whatever naming convention we decide, but I think that goes back to this: https://github.com/ga-wdi-boston/instructors/issues/24.
I think you were right there when we named this branch, so I'm happy to follow whatever process you and @gaand would like--just need to know what it is. 012/solution, 012/demo, and 012/master make more sense to me than 012/training.

**Comment by gaand** [comment]
If it's a cohort update/refresh without additional stuff, I'd say `<cohort>/<target branch>`.

So, since this update is targeting the solution branch and is an update for cohort 012, `012/solution`.

If it's a non cohort specific addition of a feature, then probably just `<feature>`.

@jrhorn424 If this makes sense as a starting place, I'll add it to the wiki.

**Comment by payne-chris-r** [comment]
I like that a lot @gaand. I'll let @jrhorn424 weigh in, but I'm happy to use that naming convention.

**Comment by payne-chris-r** [comment]
Can either @gaand or @jrhorn424 make this merge happen? Would you like me to rename the branch first?

**Comment by gaand** [comment]
You're pull contains commented out code.  You should avoid that in future.

**Pull request merged**
