### PR TITLE
017/solution

### PR DESCRIPTION
**Pull request by payne-chris-r**
Adds solution code for 017 based off of my lm01/training branch
because it's much closer to what we want on the solution branch
than what was currently there. Uses proper store and config paths
in addition to .then and .catch. Everything else looks about the
same.

### CODE REVIEW

**Comment by jrhorn424** [comment]
What's the status on this?

**Comment by payne-chris-r** [comment]
The status is: I think it should become the solution branch. The old solution branch still uses .done .fail, non-standard-js, weird formatting, and doesn't use the store/config.

**Comment by MicFin** [comment]
Looks good to me.  @jrhorn424 give a 👍 if I can complete the review and add it as solution.

**Comment by gaand** [comment]
This solution is full of extraneous `console.log`s and it's `success` and `error` handlers do not present information to the user, they rely on the console, so it should not be the solution branch without correcting those.

**Pull request merged**
